insert into CURRENCY(id,CURRENCYCODE, COUNTRY, CONVERSIONFACTOR) values (10001, 'GBP', 'GB',1.29);
insert into CURRENCY(id,CURRENCYCODE, COUNTRY, CONVERSIONFACTOR) values (10002, 'INR','IND', .014);

